name: Build and Test

on: [push, pull_request]

jobs:
  test-package:
    name: Test package
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup container
        run: |
          sudo apt install -y git curl
          curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
          sudo DEBIAN_FRONTEND=noninteractive apt install -y nodejs
        
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
            dotnet-version: 8.0.x
            
      - name: Restore dependencies
        run: dotnet restore ./src/
        
      - name: Build and test
        run: |
            dotnet build ./src/ --no-restore
            dotnet test ./src/ --no-build --logger trx --results-directory test-results
          
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
            name: test-results
            path: test-results