name: Build and Test

on: [push, pull_request]

jobs:
  test-package:
    name: Build and Test Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup container
        run: |
          sudo apt install -y git curl
          curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
          sudo DEBIAN_FRONTEND=noninteractive apt install -y nodejs
        
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
            dotnet-version: 8.0.x
            
      - name: Restore dependencies
        run: dotnet restore ./src/
        
      - name: Build and test
        run: |
            dotnet build ./src/ --no-restore
            dotnet test ./src/ --no-build --logger trx --results-directory test-results --collect:"xplat code coverage"
            zip test-results.zip test-results/*.trx

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
            name: test-results.zip
            path: test-results.zip

      - name: Install code coverage report generator 
        run: |
          mkdir code-coverage
          cp ./test-results/*/coverage.cobertura.xml ./test-results/coverage.cobertura.xml
          dotnet tool install -g dotnet-reportgenerator-globaltool 
      
      - name: Run code coverage report generator
        run: | 
          reportgenerator -reports:"test-results/coverage.cobertura.xml" -targetdir:"code-coverage" -reporttypes:Html;Badges;MarkdownSummaryGithub
          zip code-coverage.zip code-coverage